inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '2.1'
  Exclude:
    - 'test/fixtures/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/BracesAroundHashParameters:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
