inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '2.2'
  Exclude:
    - 'test/fixtures/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/BracesAroundHashParameters:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/LineLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: 'indented'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
